import { birdSpecs } from "./specs";
import type {
  CatalogProduct,
  MeatCookingMethod,
  MeatPackaging,
  MeatProductMetadata,
  MeatProductType,
  MeatSalesChannel,
} from "./types";

const channelLabels: Record<MeatSalesChannel, string> = {
  horeca: "HoReCa",
  retail: "Ритейл",
};

const productTypeLabels: Record<MeatProductType, string> = {
  steak: "Стейк",
  "large-cut": "Крупный отруб",
  "minced-meat": "Фарш",
  goulash: "Гуляш",
  fillet: "Филе",
  cutlets: "Котлеты",
};

const packagingLabels: Record<MeatPackaging, string> = {
  "large-block": "Крупный блок, вес по маркировке",
  "fixed-weight-vacuum": "Порционный вакуум, фиксированный вес",
  "tray-or-box": "Лоток или короб, вес по маркировке",
};

const cookingLabels: Record<MeatCookingMethod, string> = {
  grill: "гриль",
  fry: "жарка",
  braise: "тушение",
  bake: "запекание",
  boil: "варка",
};

function withMeatMetadata(meat: MeatProductMetadata) {
  return {
    meat,
    specs: [
      { label: "Канал поставки", value: channelLabels[meat.channel] },
      { label: "Тип продукта", value: productTypeLabels[meat.productType] },
      { label: "Фасовка", value: packagingLabels[meat.packaging] },
    ],
    tags: meat.cooking.map((method) => cookingLabels[method]),
  } satisfies Pick<CatalogProduct, "meat" | "specs" | "tags">;
}

export const catalogProducts = {
  "govyazhij-farsh-domashnij": {
    slug: "govyazhij-farsh-domashnij",
    title: "Говяжий фарш домашний",
    brand: "Мираторг",
    image: "/assets/catalog/meat/miratorg/mt_pr1.png",
    ...withMeatMetadata({
      channel: "retail",
      species: "beef",
      productType: "minced-meat",
      packaging: "tray-or-box",
      cutIds: [],
      cooking: ["fry", "grill"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить розничную поставку",
  },
  "antrekot-ohlazhdyonnyj-b2b": {
    slug: "antrekot-ohlazhdyonnyj-b2b",
    title: "Антрекот охлаждённый B2B",
    brand: "Мираторг",
    image: "/assets/catalog/meat/miratorg/mt_pr2.png",
    ...withMeatMetadata({
      channel: "horeca",
      species: "beef",
      productType: "large-cut",
      packaging: "large-block",
      cutIds: ["tolstyj-kraj"],
      cooking: ["grill", "fry"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить оптовое предложение",
  },
  "gulyash-iz-govyadiny": {
    slug: "gulyash-iz-govyadiny",
    title: "Гуляш из говядины",
    brand: "Мираторг",
    image: "/assets/catalog/meat/miratorg/mt_pr3.png",
    ...withMeatMetadata({
      channel: "retail",
      species: "beef",
      productType: "goulash",
      packaging: "tray-or-box",
      cutIds: [],
      cooking: ["braise"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить розничную поставку",
  },
  "file-kurinoe-ohlazhdennoye": {
    slug: "file-kurinoe-ohlazhdennoye",
    title: "Филе куриное охлаждённое",
    brand: "Мираторг",
    image: "/assets/catalog/meat/miratorg/mt_pr4.png",
    ...withMeatMetadata({
      channel: "retail",
      species: "poultry",
      productType: "fillet",
      packaging: "tray-or-box",
      cutIds: [],
      cooking: ["fry", "bake", "grill"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить розничную поставку",
  },
  "kotlety-domashnie-iz-svininy": {
    slug: "kotlety-domashnie-iz-svininy",
    title: "Котлеты домашние из свинины",
    brand: "Мираторг",
    image: "/assets/catalog/meat/miratorg/mt_pr5.png",
    ...withMeatMetadata({
      channel: "retail",
      species: "pork",
      productType: "cutlets",
      packaging: "tray-or-box",
      cutIds: [],
      cooking: ["fry", "bake"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить розничную поставку",
  },
  "steyk-ribaj-prajm": {
    slug: "steyk-ribaj-prajm",
    title: "Стейк Рибай Прайм",
    brand: "Мираторг",
    image: "/assets/catalog/meat/miratorg/mt_pr6.png",
    ...withMeatMetadata({
      channel: "retail",
      species: "beef",
      productType: "steak",
      packaging: "fixed-weight-vacuum",
      cutIds: ["tolstyj-kraj"],
      cooking: ["grill", "fry"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить розничную поставку",
  },
  "steyk-striploin": {
    slug: "steyk-striploin",
    title: "Стейк Стриплоин",
    brand: "Primebeef",
    image: "/assets/catalog/meat/primebeef/primebeef2.png",
    ...withMeatMetadata({
      channel: "horeca",
      species: "beef",
      productType: "steak",
      packaging: "fixed-weight-vacuum",
      cutIds: ["tonkij-kraj"],
      cooking: ["grill", "fry"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить оптовое предложение",
  },
  "file-minon-tenderloin": {
    slug: "file-minon-tenderloin",
    title: "Филе-миньон (Тендерлоин)",
    brand: "Primebeef",
    image: "/assets/catalog/meat/primebeef/primebeef3.png",
    ...withMeatMetadata({
      channel: "horeca",
      species: "beef",
      productType: "fillet",
      packaging: "fixed-weight-vacuum",
      cutIds: [],
      cooking: ["grill", "fry"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить оптовое предложение",
  },
  "steyk-ribaj-prajm-primebeef": {
    slug: "steyk-ribaj-prajm-primebeef",
    title: "Стейк Рибай Прайм",
    brand: "Primebeef",
    image: "/assets/catalog/meat/primebeef/primebeef1.png",
    ...withMeatMetadata({
      channel: "horeca",
      species: "beef",
      productType: "steak",
      packaging: "fixed-weight-vacuum",
      cutIds: ["tolstyj-kraj"],
      cooking: ["grill", "fry"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить оптовое предложение",
  },
  "tolstyj-kraj": {
    slug: "tolstyj-kraj",
    title: "Толстый край",
    brand: "Primebeef",
    image: "/assets/catalog/meat/primebeef/primebeef4.png",
    ...withMeatMetadata({
      channel: "horeca",
      species: "beef",
      productType: "large-cut",
      packaging: "large-block",
      cutIds: ["tolstyj-kraj"],
      cooking: ["grill", "bake"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить оптовое предложение",
  },
  "steyk-ribaj-v-vakuume": {
    slug: "steyk-ribaj-v-vakuume",
    title: "Стейк Рибай в вакууме",
    brand: "Primebeef",
    image: "/assets/catalog/meat/primebeef/pb1.png",
    ...withMeatMetadata({
      channel: "retail",
      species: "beef",
      productType: "steak",
      packaging: "fixed-weight-vacuum",
      cutIds: ["tolstyj-kraj"],
      cooking: ["grill", "fry"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить розничную поставку",
  },
  "steyk-nyu-york": {
    slug: "steyk-nyu-york",
    title: "Стейк Нью-Йорк",
    brand: "Primebeef",
    image: "/assets/catalog/meat/primebeef/pb2.png",
    ...withMeatMetadata({
      channel: "retail",
      species: "beef",
      productType: "steak",
      packaging: "fixed-weight-vacuum",
      cutIds: ["tonkij-kraj"],
      cooking: ["grill", "fry"],
    }),
    recommendation: "Рекомендуемое пиво: IPA, Porter",
    buttonLabel: "Запросить розничную поставку",
  },
  "paulaner-hefe-weissbier": {
    slug: "paulaner-hefe-weissbier",
    title: "Paulaner Hefe-Weißbier",
    brand: "Paulaner",
    image: "/assets/catalog/beer/beer1.png",
    specs: [
      { label: "Крепость (Алкоголь)", value: "5.5%" },
      { label: "Горечь (IBU)", value: "12" },
    ],
    tags: ["Пшеничное"],
    recommendation: "Идеальное сочетание с мясом: Стейк Рибай, Антрекот",
    buttonLabel: "Запросить поставку",
  },
  "guinness-draught": {
    slug: "guinness-draught",
    title: "Guinness Draught",
    brand: "Guinness",
    image: "/assets/catalog/beer/beer2.png",
    specs: [
      { label: "Крепость (Алкоголь)", value: "4.2%" },
      { label: "Горечь (IBU)", value: "45" },
    ],
    tags: ["Стаут"],
    recommendation: "Идеальное сочетание с мясом: Гуляш из говядины, Грудинка",
    buttonLabel: "Запросить поставку",
  },
  "chimay-blue": {
    slug: "chimay-blue",
    title: "Chimay Blue",
    brand: "Chimay",
    image: "/assets/catalog/beer/beer3.png",
    specs: [
      { label: "Крепость (Алкоголь)", value: "9.0%" },
      { label: "Горечь (IBU)", value: "30" },
    ],
    tags: ["Тёмный эль"],
    recommendation: "Идеальное сочетание с мясом: Филе-миньон, Оковалок",
    buttonLabel: "Запросить поставку",
  },
  "pilsner-urquell": {
    slug: "pilsner-urquell",
    title: "Pilsner Urquell",
    brand: "Pilsner Urquell",
    image: "/assets/catalog/beer/beer4.png",
    specs: [
      { label: "Крепость (Алкоголь)", value: "4.4%" },
      { label: "Горечь (IBU)", value: "40" },
    ],
    tags: ["Лагер"],
    recommendation: "Идеальное сочетание с мясом: Куриное филе, Индейка",
    buttonLabel: "Запросить поставку",
  },
  "brewdog-punk-ipa": {
    slug: "brewdog-punk-ipa",
    title: "BrewDog Punk IPA",
    brand: "BrewDog",
    image: "/assets/catalog/beer/beer5.png",
    specs: [
      { label: "Крепость (Алкоголь)", value: "5.4%" },
      { label: "Горечь (IBU)", value: "35" },
    ],
    tags: ["IPA"],
    recommendation: "Идеальное сочетание с мясом: Говяжий фарш, Котлеты",
    buttonLabel: "Запросить поставку",
  },
  "hoegaarden": {
    slug: "hoegaarden",
    title: "Hoegaarden",
    brand: "Hoegaarden",
    image: "/assets/catalog/beer/beer6.png",
    specs: [
      { label: "Крепость (Алкоголь)", value: "4.9%" },
      { label: "Горечь (IBU)", value: "15" },
    ],
    tags: ["Светлое пшеничное"],
    recommendation: "Идеальное сочетание с мясом: Утиная грудка, Перепел",
    buttonLabel: "Запросить поставку",
  },
  "file-kurinoe-fermerskoe": {
    slug: "file-kurinoe-fermerskoe",
    title: "Филе куриное фермерское",
    brand: "Петелинка",
    image: "/assets/catalog/bird/bird1.png",
    specs: birdSpecs,
    tags: ["запекание", "варка"],
    recommendation: "Рекомендуемое пиво: Blond Ale, Wheat",
    buttonLabel: "Запросить коммерческое предложение",
    badge: "ферма",
  },
  "utinaya-grudka": {
    slug: "utinaya-grudka",
    title: "Утиная грудка охлаждённая",
    brand: "Озёрская утка",
    image: "/assets/catalog/bird/bird2.png",
    specs: birdSpecs,
    tags: ["жарка", "запекание"],
    recommendation: "Рекомендуемое пиво: Dubbel, Amber Ale",
    buttonLabel: "Запросить коммерческое предложение",
    badge: "ферма",
  },
  "indejka-file-grudki": {
    slug: "indejka-file-grudki",
    title: "Индейка филе грудки",
    brand: "Индилайт",
    image: "/assets/catalog/bird/bird3.png",
    specs: birdSpecs,
    tags: ["запекание", "гриль"],
    recommendation: "Рекомендуемое пиво: Pale Ale, Lager",
    buttonLabel: "Запросить коммерческое предложение",
    badge: "ферма",
  },
  "perepel-tushka": {
    slug: "perepel-tushka",
    title: "Перепел тушка охлаждённая",
    brand: "Перепёлкино",
    image: "/assets/catalog/bird/bird4.png",
    specs: birdSpecs,
    tags: ["запекание", "гриль"],
    recommendation: "Рекомендуемое пиво: Pilsner, Belgian Single",
    buttonLabel: "Запросить коммерческое предложение",
    badge: "ферма",
  },
  "kurinye-bedra": {
    slug: "kurinye-bedra",
    title: "Куриные бёдра охлаждённые",
    brand: "Петелинка",
    image: "/assets/catalog/bird/bird5.png",
    specs: birdSpecs,
    tags: ["жарка", "гриль"],
    recommendation: "Рекомендуемое пиво: IPA, APA",
    buttonLabel: "Запросить коммерческое предложение",
    badge: "ферма",
  },
  "krylya-kurinye": {
    slug: "krylya-kurinye",
    title: "Крылья куриные фермерские",
    brand: "Петелинка",
    image: "/assets/catalog/bird/bird6.png",
    specs: birdSpecs,
    tags: ["жарка", "запекание"],
    recommendation: "Рекомендуемое пиво: Double IPA, Porter",
    buttonLabel: "Запросить коммерческое предложение",
    badge: "ферма",
  },
} satisfies Record<string, CatalogProduct>;

export type CatalogProductSlug = keyof typeof catalogProducts;
